// <auto-generated />
using HackerBank.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HackerBank.API.Migrations
{
    [DbContext(typeof(HackerBankDbContext))]
    [Migration("20260328054720_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HackerBank.API.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Balance")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 1985.4m,
                            Balance = "$12,234.45",
                            Date = "2026-03-28",
                            Description = "HACKERBANK INC. DES:CCD+ ID: 33375894749",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Amount = 3200m,
                            Balance = "$10,249.05",
                            Date = "2026-03-27",
                            Description = "ACH TRANSFER - PAYROLL DEPOSIT",
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            Amount = 59.99m,
                            Balance = "$7,049.05",
                            Date = "2026-03-27",
                            Description = "AMAZON.COM PURCHASE",
                            Type = 1
                        },
                        new
                        {
                            Id = 4,
                            Amount = 6.75m,
                            Balance = "$7,109.04",
                            Date = "2026-03-26",
                            Description = "STARBUCKS #4823 COFFEE",
                            Type = 1
                        },
                        new
                        {
                            Id = 5,
                            Amount = 500m,
                            Balance = "$7,115.79",
                            Date = "2026-03-26",
                            Description = "ONLINE TRANSFER FROM SAVINGS",
                            Type = 0
                        },
                        new
                        {
                            Id = 6,
                            Amount = 13.99m,
                            Balance = "$6,615.79",
                            Date = "2026-03-25",
                            Description = "NETFLIX SUBSCRIPTION",
                            Type = 1
                        },
                        new
                        {
                            Id = 7,
                            Amount = 87.34m,
                            Balance = "$6,629.78",
                            Date = "2026-03-25",
                            Description = "WHOLE FOODS MARKET",
                            Type = 1
                        },
                        new
                        {
                            Id = 8,
                            Amount = 22.5m,
                            Balance = "$6,717.12",
                            Date = "2026-03-24",
                            Description = "UBER TECHNOLOGIES",
                            Type = 1
                        },
                        new
                        {
                            Id = 9,
                            Amount = 12.48m,
                            Balance = "$6,739.62",
                            Date = "2026-03-24",
                            Description = "INTEREST PAYMENT",
                            Type = 0
                        },
                        new
                        {
                            Id = 10,
                            Amount = 200m,
                            Balance = "$6,727.14",
                            Date = "2026-03-23",
                            Description = "ATM WITHDRAWAL - 5TH AVE",
                            Type = 1
                        },
                        new
                        {
                            Id = 11,
                            Amount = 9.99m,
                            Balance = "$6,927.14",
                            Date = "2026-03-22",
                            Description = "SPOTIFY PREMIUM",
                            Type = 1
                        },
                        new
                        {
                            Id = 12,
                            Amount = 750m,
                            Balance = "$6,937.13",
                            Date = "2026-03-22",
                            Description = "DIRECT DEPOSIT - FREELANCE",
                            Type = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
